### ISSUE TITLE
Add "Extra info" to BMLT_TABLE display

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/bmlt-satellite-base-class#20]
Groups have requested that we include the "Extra Info" in the BMLT_TABLE shortcode.
This information displays critical information to assist members in locating certain meetings.
Is this possible?  Either as a link to more info or as an additional column?

**Comment by pjaudiomv** [comment]
This should be fairly simple, the comments field is already on there.

**Comment by pjaudiomv** [comment]
I'm adding this in now, I am going to make it hidden by default with all of the themes except australia and nerna unless anyone thinks different. @ChrisMarshallNY

**Comment by pjaudiomv** [comment]
actual I'm leaning towards just letting the end user make that decision to hide, need more input.

**Comment by ChrisMarshallNY** [comment]
Not sure if I have anything to add, except that simple has both table and block mode, so you'll need to make sure that the new column has the appropriate CSS hooks.

**Comment by ChrisMarshallNY** [comment]
It may be best to have a new row (increase the rowspan), with the info.

**Comment by pjaudiomv** [comment]
cool thanks, that's what I'm gonna do, new row.

**Comment by pjaudiomv** [comment]
this will be in next release probably whenever number #17 is solved
